create table if not exists public.entity_search_documents (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('item', 'container')),
  entity_id bigint not null,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  source_type text not null check (source_type in ('text', 'image')),
  name text,
  entity_type_name text,
  content text,
  photo_url text,
  embedding_model text not null,
  embedding extensions.vector(1024) not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint entity_search_documents_unique_source unique (entity_type, entity_id, source_type),
  constraint entity_search_documents_source_content_check check (
    (source_type = 'text' and content is not null and photo_url is null)
    or (source_type = 'image' and photo_url is not null)
  )
);

create index if not exists entity_search_documents_tenant_entity_idx
  on public.entity_search_documents (tenant_id, entity_type, entity_id);

create index if not exists entity_search_documents_embedding_hnsw_idx
  on public.entity_search_documents
  using hnsw (embedding extensions.vector_cosine_ops);

alter table public.entity_search_documents enable row level security;

drop policy if exists "Tenant read entity_search_documents" on public.entity_search_documents;
create policy "Tenant read entity_search_documents"
  on public.entity_search_documents
  for select
  to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

drop policy if exists "Tenant insert entity_search_documents" on public.entity_search_documents;
create policy "Tenant insert entity_search_documents"
  on public.entity_search_documents
  for insert
  to authenticated
  with check (tenant_id = any(tenant.user_tenant_ids()));

drop policy if exists "Tenant update entity_search_documents" on public.entity_search_documents;
create policy "Tenant update entity_search_documents"
  on public.entity_search_documents
  for update
  to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()))
  with check (tenant_id = any(tenant.user_tenant_ids()));

drop policy if exists "Tenant delete entity_search_documents" on public.entity_search_documents;
create policy "Tenant delete entity_search_documents"
  on public.entity_search_documents
  for delete
  to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

grant select, insert, update, delete on public.entity_search_documents to authenticated;
grant usage, select on sequence public.entity_search_documents_id_seq to authenticated;

create or replace function public.set_entity_search_documents_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists entity_search_documents_set_updated_at on public.entity_search_documents;
create trigger entity_search_documents_set_updated_at
before update on public.entity_search_documents
for each row
execute function public.set_entity_search_documents_updated_at();

insert into public.entity_search_documents (
  entity_type,
  entity_id,
  tenant_id,
  source_type,
  name,
  entity_type_name,
  content,
  photo_url,
  embedding_model,
  embedding,
  created_at,
  updated_at
)
select
  'item' as entity_type,
  d.item_id as entity_id,
  d.tenant_id,
  d.source_type,
  i.name,
  et.name as entity_type_name,
  d.content,
  d.photo_url,
  d.embedding_model,
  d.embedding,
  d.created_at,
  d.updated_at
from public.item_search_documents d
join public.items i on i.id = d.item_id
left join public.entity_types et on et.id = i.item_type_id and et.deleted_at is null
on conflict (entity_type, entity_id, source_type)
do update set
  tenant_id = excluded.tenant_id,
  name = excluded.name,
  entity_type_name = excluded.entity_type_name,
  content = excluded.content,
  photo_url = excluded.photo_url,
  embedding_model = excluded.embedding_model,
  embedding = excluded.embedding,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

drop function if exists public.search_entities_by_embedding(
  text,
  bigint,
  text[],
  boolean,
  integer,
  integer,
  double precision
);

create or replace function public.search_entities_by_embedding(
  query_embedding_text text,
  filter_tenant_id bigint,
  entity_types text[] default array['item', 'container']::text[],
  show_deleted boolean default false,
  page_limit integer default 20,
  page_offset integer default 0,
  similarity_threshold double precision default 0.25
)
returns table (
  entity_type text,
  entity_id bigint,
  similarity double precision,
  match_source text,
  total_count bigint
)
language sql
stable
security definer
set search_path = public, tenant, extensions, pg_temp
as $$
with query_vector as (
  select query_embedding_text::extensions.vector(1024) as embedding
),
raw_matches as (
  select
    d.entity_type,
    d.entity_id,
    d.source_type,
    1 - (d.embedding <=> q.embedding) as similarity,
    row_number() over (
      partition by d.entity_type, d.entity_id
      order by
        1 - (d.embedding <=> q.embedding) desc,
        case when d.source_type = 'image' then 0 else 1 end,
        d.updated_at desc
    ) as rn
  from public.entity_search_documents d
  cross join query_vector q
  where
    filter_tenant_id is not null
    and filter_tenant_id = any(tenant.user_tenant_ids())
    and d.tenant_id = filter_tenant_id
    and d.entity_type = any(entity_types)
),
best_matches as (
  select
    entity_type,
    entity_id,
    source_type as match_source,
    similarity
  from raw_matches
  where rn = 1 and similarity >= similarity_threshold
),
filtered_entities as (
  select
    'item'::text as entity_type,
    i.id as entity_id,
    i.created_at,
    bm.similarity,
    bm.match_source
  from public.items i
  join best_matches bm
    on bm.entity_type = 'item'
    and bm.entity_id = i.id
  where
    (filter_tenant_id = any(tenant.user_tenant_ids()) and i.tenant_id = filter_tenant_id)
    and case when show_deleted then i.deleted_at is not null else i.deleted_at is null end

  union all

  select
    'container'::text as entity_type,
    c.id as entity_id,
    c.created_at,
    bm.similarity,
    bm.match_source
  from public.containers c
  join best_matches bm
    on bm.entity_type = 'container'
    and bm.entity_id = c.id
  where
    (filter_tenant_id = any(tenant.user_tenant_ids()) and c.tenant_id = filter_tenant_id)
    and case when show_deleted then c.deleted_at is not null else c.deleted_at is null end
),
filtered_count as (
  select count(*)::bigint as total_count from filtered_entities
),
paged_entities as (
  select *
  from filtered_entities
  order by similarity desc, created_at desc
  offset page_offset
  limit page_limit
)
select
  p.entity_type,
  p.entity_id,
  p.similarity,
  p.match_source,
  fc.total_count
from paged_entities p
cross join filtered_count fc;
$$;

grant execute on function public.search_entities_by_embedding(
  text,
  bigint,
  text[],
  boolean,
  integer,
  integer,
  double precision
) to anon, authenticated;
