-- Таблица мебели (родитель для мест; мебель находится в помещениях)
create table if not exists public.furniture (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name varchar,
  room_id bigint not null references public.rooms(id),
  furniture_type_id bigint references public.entity_types(id),
  deleted_at timestamptz,
  photo_url text
);

comment on table public.furniture is 'Мебель в помещениях. Места всегда находятся в мебели. RLS политики разрешают доступ всем аутентифицированным пользователям.';

create index if not exists idx_furniture_room_id on public.furniture(room_id);
create index if not exists idx_furniture_furniture_type_id on public.furniture(furniture_type_id);
create index if not exists idx_furniture_deleted_at on public.furniture(deleted_at);

-- Добавить furniture в entity_category
alter table public.entity_types drop constraint if exists entity_types_entity_category_check;
alter table public.entity_types add constraint entity_types_entity_category_check
  check (entity_category::text = any (array['place'::text, 'container'::text, 'room'::text, 'item'::text, 'building'::text, 'furniture'::text]));

-- transitions: добавить furniture в destination_type
alter table public.transitions drop constraint if exists transitions_destination_type_check;
alter table public.transitions add constraint transitions_destination_type_check
  check (destination_type is null or destination_type::text = any (array['place'::text, 'container'::text, 'room'::text, 'furniture'::text]));

-- RLS для furniture
alter table public.furniture enable row level security;

create policy "Allow authenticated users to read furniture"
  on public.furniture for select to authenticated using (true);

create policy "Allow authenticated users to insert furniture"
  on public.furniture for insert to authenticated with check (true);

create policy "Allow authenticated users to update furniture"
  on public.furniture for update to authenticated using (true);

create policy "Allow authenticated users to delete furniture"
  on public.furniture for delete to authenticated using (true);
