-- Таблица зданий (родитель для помещений)
create table if not exists public.buildings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name varchar,
  deleted_at timestamptz,
  photo_url text,
  building_type_id bigint references public.entity_types(id)
);

comment on table public.buildings is 'Здания, в которых находятся помещения. RLS политики разрешают доступ всем аутентифицированным пользователям.';

create index if not exists idx_buildings_building_type_id on public.buildings(building_type_id);
create index if not exists idx_buildings_deleted_at on public.buildings(deleted_at);

-- Добавить building_id в rooms
alter table public.rooms
  add column if not exists building_id bigint references public.buildings(id);

create index if not exists idx_rooms_building_id on public.rooms(building_id);

-- Добавить building в entity_category
alter table public.entity_types drop constraint if exists entity_types_entity_category_check;
alter table public.entity_types add constraint entity_types_entity_category_check
  check (entity_category::text = any (array['place'::text, 'container'::text, 'room'::text, 'item'::text, 'building'::text]));

-- RLS для buildings
alter table public.buildings enable row level security;

create policy "Allow authenticated users to read buildings"
  on public.buildings for select to authenticated using (true);

create policy "Allow authenticated users to insert buildings"
  on public.buildings for insert to authenticated with check (true);

create policy "Allow authenticated users to update buildings"
  on public.buildings for update to authenticated using (true);

create policy "Allow authenticated users to delete buildings"
  on public.buildings for delete to authenticated using (true);
