-- Multi-tenancy: tenants, memberships, invitations, tenant_id columns, RLS
-- T003-T008

-- Create schema for tenant helper functions
create schema if not exists tenant;

-- T003: New tables
create table if not exists public.tenants (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name varchar(255),
  deleted_at timestamptz
);

create table if not exists public.tenant_memberships (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role varchar(20) not null default 'member',
  unique (tenant_id, user_id)
);

create table if not exists public.tenant_invitations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  inviter_id uuid not null references auth.users(id) on delete cascade,
  invitee_email varchar(255),
  status varchar(20) not null default 'pending',
  token varchar(64) not null unique,
  expires_at timestamptz not null default (now() + interval '7 days')
);

-- T005: Helper functions (before RLS so we can use them in policies)
create or replace function tenant.user_tenant_ids()
returns bigint[] language sql stable security definer
set search_path = public
as $$
  select coalesce(array_agg(tm.tenant_id), '{}')::bigint[]
  from tenant_memberships tm
  where tm.user_id = auth.uid();
$$;

create or replace function tenant.is_member(p_tenant_id bigint)
returns boolean language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from tenant_memberships tm
    where tm.tenant_id = p_tenant_id and tm.user_id = auth.uid()
  );
$$;

-- T004: Add tenant_id to entity tables (nullable first for migration)
alter table public.buildings add column if not exists tenant_id bigint references public.tenants(id);
alter table public.rooms add column if not exists tenant_id bigint references public.tenants(id);
alter table public.furniture add column if not exists tenant_id bigint references public.tenants(id);
alter table public.places add column if not exists tenant_id bigint references public.tenants(id);
alter table public.containers add column if not exists tenant_id bigint references public.tenants(id);
alter table public.items add column if not exists tenant_id bigint references public.tenants(id);
alter table public.transitions add column if not exists tenant_id bigint references public.tenants(id);

-- T008: Migrate existing data — create default tenant, assign all rows, add all users as members
do $$
declare
  default_tenant_id bigint;
  usr record;
begin
  -- Create default tenant
  insert into public.tenants (name) values ('Мой склад') returning id into default_tenant_id;

  -- Add all auth.users as members
  for usr in select id from auth.users
  loop
    insert into public.tenant_memberships (tenant_id, user_id, role)
    values (default_tenant_id, usr.id, 'member')
    on conflict (tenant_id, user_id) do nothing;
  end loop;

  -- Assign all existing data to default tenant
  update public.buildings set tenant_id = default_tenant_id where tenant_id is null;
  update public.rooms set tenant_id = default_tenant_id where tenant_id is null;
  update public.furniture set tenant_id = default_tenant_id where tenant_id is null;
  update public.places set tenant_id = default_tenant_id where tenant_id is null;
  update public.containers set tenant_id = default_tenant_id where tenant_id is null;
  update public.items set tenant_id = default_tenant_id where tenant_id is null;
  update public.transitions set tenant_id = default_tenant_id where tenant_id is null;
end $$;

-- Set NOT NULL
alter table public.buildings alter column tenant_id set not null;
alter table public.rooms alter column tenant_id set not null;
alter table public.furniture alter column tenant_id set not null;
alter table public.places alter column tenant_id set not null;
alter table public.containers alter column tenant_id set not null;
alter table public.items alter column tenant_id set not null;
alter table public.transitions alter column tenant_id set not null;

-- T007: Indexes
create index if not exists idx_tenant_memberships_user_id on public.tenant_memberships(user_id);
create index if not exists idx_tenant_memberships_tenant_id on public.tenant_memberships(tenant_id);
create index if not exists idx_tenant_invitations_token on public.tenant_invitations(token);
create index if not exists idx_tenant_invitations_tenant_id on public.tenant_invitations(tenant_id);
create index if not exists idx_buildings_tenant_id on public.buildings(tenant_id);
create index if not exists idx_rooms_tenant_id on public.rooms(tenant_id);
create index if not exists idx_furniture_tenant_id on public.furniture(tenant_id);
create index if not exists idx_places_tenant_id on public.places(tenant_id);
create index if not exists idx_containers_tenant_id on public.containers(tenant_id);
create index if not exists idx_items_tenant_id on public.items(tenant_id);
create index if not exists idx_transitions_tenant_id on public.transitions(tenant_id);

-- T006: RLS for new tables
alter table public.tenants enable row level security;
alter table public.tenant_memberships enable row level security;
alter table public.tenant_invitations enable row level security;

-- Drop existing RLS policies on entity tables (names may vary)
do $$
declare
  pol record;
  tbl text[] := array['rooms', 'places', 'containers', 'items', 'transitions', 'buildings', 'furniture'];
  t text;
begin
  for t in select unnest(tbl)
  loop
    for pol in select policyname from pg_policies where tablename = t and schemaname = 'public'
    loop
      execute format('drop policy if exists %I on public.%I', pol.policyname, t);
    end loop;
  end loop;
end $$;

-- Tenants: members can read; members can insert (create)
create policy "Members read tenants" on public.tenants for select to authenticated
  using (id = any(tenant.user_tenant_ids()));

create policy "Members create tenants" on public.tenants for insert to authenticated
  with check (true);

create policy "Members update own tenants" on public.tenants for update to authenticated
  using (id = any(tenant.user_tenant_ids()));

create policy "Members delete own tenants" on public.tenants for delete to authenticated
  using (id = any(tenant.user_tenant_ids()));

-- Tenant memberships: members of a tenant can read memberships for that tenant
create policy "Members read memberships" on public.tenant_memberships for select to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

create policy "Members insert memberships" on public.tenant_memberships for insert to authenticated
  with check (tenant_id = any(tenant.user_tenant_ids()));

create policy "Members delete memberships" on public.tenant_memberships for delete to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

-- Tenant invitations
create policy "Members read invitations" on public.tenant_invitations for select to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

create policy "Members create invitations" on public.tenant_invitations for insert to authenticated
  with check (tenant_id = any(tenant.user_tenant_ids()));

create policy "Members update invitations" on public.tenant_invitations for update to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

-- Entity tables: tenant-scoped
create policy "Tenant read buildings" on public.buildings for select to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant insert buildings" on public.buildings for insert to authenticated
  with check (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant update buildings" on public.buildings for update to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant delete buildings" on public.buildings for delete to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

create policy "Tenant read rooms" on public.rooms for select to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant insert rooms" on public.rooms for insert to authenticated
  with check (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant update rooms" on public.rooms for update to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant delete rooms" on public.rooms for delete to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

create policy "Tenant read furniture" on public.furniture for select to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant insert furniture" on public.furniture for insert to authenticated
  with check (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant update furniture" on public.furniture for update to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant delete furniture" on public.furniture for delete to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

create policy "Tenant read places" on public.places for select to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant insert places" on public.places for insert to authenticated
  with check (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant update places" on public.places for update to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant delete places" on public.places for delete to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

create policy "Tenant read containers" on public.containers for select to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant insert containers" on public.containers for insert to authenticated
  with check (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant update containers" on public.containers for update to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant delete containers" on public.containers for delete to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

create policy "Tenant read items" on public.items for select to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant insert items" on public.items for insert to authenticated
  with check (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant update items" on public.items for update to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant delete items" on public.items for delete to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));

create policy "Tenant read transitions" on public.transitions for select to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant insert transitions" on public.transitions for insert to authenticated
  with check (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant update transitions" on public.transitions for update to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
create policy "Tenant delete transitions" on public.transitions for delete to authenticated
  using (tenant_id = any(tenant.user_tenant_ids()));
